// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApmInP9D7TKX2UVegOUkH8hth6BSB8AZk',
    appId: '1:69247963633:web:fe0e22072e0dea66f57450',
    messagingSenderId: '69247963633',
    projectId: 'talki-app-70ff9',
    authDomain: 'talki-app-70ff9.firebaseapp.com',
    storageBucket: 'talki-app-70ff9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACR-3rIe-uymAfNGGWBsUSNc22NxgJvNI',
    appId: '1:69247963633:android:92340e9dfd9dfdaff57450',
    messagingSenderId: '69247963633',
    projectId: 'talki-app-70ff9',
    storageBucket: 'talki-app-70ff9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOJfjYijpNS7VIWEjM__gJgWBXzvCoLdw',
    appId: '1:69247963633:ios:90843274fa89668ef57450',
    messagingSenderId: '69247963633',
    projectId: 'talki-app-70ff9',
    storageBucket: 'talki-app-70ff9.appspot.com',
    iosClientId: '69247963633-b04eg70m4kts4gksro0dn9itupqqgrpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.talki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOJfjYijpNS7VIWEjM__gJgWBXzvCoLdw',
    appId: '1:69247963633:ios:90843274fa89668ef57450',
    messagingSenderId: '69247963633',
    projectId: 'talki-app-70ff9',
    storageBucket: 'talki-app-70ff9.appspot.com',
    iosClientId: '69247963633-b04eg70m4kts4gksro0dn9itupqqgrpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.talki',
  );
}
