// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyahevGscBd_3BrTJuZOgKCByqawlJW7w',
    appId: '1:221467203358:web:09542d43c8432aa90c1b0f',
    messagingSenderId: '221467203358',
    projectId: 'talker-f1ac5',
    authDomain: 'talker-f1ac5.firebaseapp.com',
    storageBucket: 'talker-f1ac5.appspot.com',
    measurementId: 'G-5BS0KPGLKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsombzCvSmM7mSbnIkvVcwv1FmvDS18KU',
    appId: '1:221467203358:android:f13a4fb85c2b034f0c1b0f',
    messagingSenderId: '221467203358',
    projectId: 'talker-f1ac5',
    storageBucket: 'talker-f1ac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIF-le6iaq03ZZIIP1jmB3uewmWTXW6x8',
    appId: '1:221467203358:ios:3dfd4c5504adbcb40c1b0f',
    messagingSenderId: '221467203358',
    projectId: 'talker-f1ac5',
    storageBucket: 'talker-f1ac5.appspot.com',
    iosClientId: '221467203358-q4s0r0or4qtikea0o46qhl356i9ep69m.apps.googleusercontent.com',
    iosBundleId: 'com.IFLap.talker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIF-le6iaq03ZZIIP1jmB3uewmWTXW6x8',
    appId: '1:221467203358:ios:3dfd4c5504adbcb40c1b0f',
    messagingSenderId: '221467203358',
    projectId: 'talker-f1ac5',
    storageBucket: 'talker-f1ac5.appspot.com',
    iosClientId: '221467203358-q4s0r0or4qtikea0o46qhl356i9ep69m.apps.googleusercontent.com',
    iosBundleId: 'com.IFLap.talker',
  );
}
